### PR TITLE
fix crash in verbose mode

### PR DESCRIPTION
**Pull request by JohnnyLChang**

### CODE REVIEW

**Comment by aguinet** [comment]
Thanks for this! I fixed this one in the next release (still hasn't pushed commits yet). The actual fix is (uintptr_t)Buf, because &Buf would give the address of the Buf variable, which isn't quite useful ;)

**Comment by JohnnyLChang** [comment]
Indeed, got it.

2017年6月3日 16:29，"Adrien Guinet" <notifications@github.com>寫道：

**Comment by JohnnyLChang** [comment]
I checked the current implementation, the displayed address was created by
vector heap, not the real memory address.
am I right? I am not sure...

P: 00BAEAB0
Q: 00BAEA28
Key generated, zeroying data at 00baeb60...
Will destroy key...
Will release ctx...
MemInfo.BaseAddress009B0000
MemInfo.BaseAddress00A20000
MemInfo.BaseAddress00AA8000
MemInfo.BaseAddress00BAC000
Found P at 00BAEAB0 => I changed to memory block address with offset
Found P at heap 026E2310 => this was created by std::vector<uint8_t> Buf;
@process.cpp #138
Found Q at 00BAEA28
Found Q at heap 026E2288

I check the heap stack trace to find out that the Prime number address was
create by vector and not in Windows API section.
that's why I found it.


2017-06-03 16:32 GMT+08:00 Johnny Chang <riversnow@gmail.com>:

**Comment by JohnnyLChang** [comment]
after I correct the memory address comparison. the information should be
correct.
actually, it found the same block.

Results:
The Windows Cryptograhic API does not seem to leak secrets on this Windows
version :/
Wannakey has close to zero chance to recover the private key. Sorry :/

Please report the formatted result below to
https://github.com/aguinet/wannakey/issues/5:
Windows 10.0.15063 (Win10 or Server 2016) / Intel 64-bit / No leak

2017-06-03 19:24 GMT+08:00 Johnny Chang <riversnow@gmail.com>:

**Comment by aguinet** [comment]
Yep I failed on this one... It has been corrected on the commit I just pushed a few hours ago!

**Comment by JohnnyLChang** [comment]
Great!!

2017年6月3日 19:34，"Adrien Guinet" <notifications@github.com>寫道：

**Pull request closed without merging**
